### ISSUE TITLE
What is magnitude_scale?

### ISSUE THREAD

**Issue by sandydf** [daizhirui/BEVNet#3]
Thanks for the interesting work! Could you tell me the meaning of variable magnitude_scale when computing the map loss?

**Comment by daizhirui** [comment]
It is used to scale the crowd counting when computing the loss: [https://github.com/daizhirui/BEVNet/blob/d45a20613077b5bedf50e624806172f876356d82/src/models/loss_fns/bev_loss.py#L51](https://github.com/daizhirui/BEVNet/blob/d45a20613077b5bedf50e624806172f876356d82/src/models/loss_fns/bev_loss.py#L51)

**Comment by sandydf** [comment]
I'm` sorry, I still don't understand. Like here pred and target should be the same order of magnitude, why is target multiplied by scale and pred not?

> 
https://github.com/daizhirui/BEVNet/blob/master/src/models/loss_fns/magnified_loss.py#L13
```
  return self.loss_fn(pred, target * self.magnitude_scale)
```

Or why the two use different scale?
```
pred_cnt = self.get_cnt(pred_dict[k], self.magnitude_scale)
target_cnt = self.get_cnt(target_dict[k], 1.)     
```

**Comment by daizhirui** [comment]
Since the map loss is relatively smaller, we times it by `magnitude_scale`:
https://github.com/daizhirui/BEVNet/blob/d45a20613077b5bedf50e624806172f876356d82/src/models/loss_fns/bev_loss.py#L25
https://github.com/daizhirui/BEVNet/blob/d45a20613077b5bedf50e624806172f876356d82/src/models/loss_fns/magnified_loss.py#L13

Then, the counting loss should be computed without the scale, so we have to divide the prediction by `magnitude_scale` because the counting is the sum of the map, of which the prediction is supervised to be `magnitude_scale` times large.
https://github.com/daizhirui/BEVNet/blob/d45a20613077b5bedf50e624806172f876356d82/src/models/loss_fns/bev_loss.py#L51

**Comment by sandydf** [comment]
Thanks!
