### ISSUE TITLE
Question about BEV map generation

### ISSUE THREAD

**Issue by chase1aa1** [daizhirui/BEVNet#5]
Thanks for the interesting work!
But I found that in some images, the number of points in the BEV map is fewer than that in the IV map. Should only BEV coordinates with both x and y positive be used to generate the BEV map?

**Comment by chase1aa1** [comment]
Further more, if I modify these two lines of code, can I obtain a Bird's Eye View (BEV) map generated using all points?
![0](https://github.com/daizhirui/BEVNet/assets/152474437/129d43d2-dc19-497c-908d-3d979fab6b68)

**Comment by daizhirui** [comment]
Thanks for asking!

We lost some points sometimes because it is impractical to make the BEV map contain the whole ground due to the limited BEV image size. Imagine that you have a camera with zero pitch angle record the scene. The image you get will capture peoples very far away, meaning that the actual covered ground area is pretty long along the direction that your camera points to, which is difficult to make a BEV map contains the whole area.

The code you mark guarantees the indexing is not out-of-bound. I don't think you can remove it.

**Comment by chase1aa1** [comment]
Thank you for your reply
